- name: TEST SHELL MODULE
  hosts: all
  tasks:
    - name: DISPLAY USER
      shell: whoami
    - name:  DISPLAY CWD
      shell: echo $HOME
      
    - name: create a text file in $HOME only if it doesn't already exist
      shell: echo "Hello, World!" > $HOME/test_file.txt
      args:
        creates: "$HOME/test_file.txt"  
        
    - name: create a text file in /tmp 
      shell: echo "Hello, World!" > /tmp/test_file.txt
      args:
        creates: "/tmp/test_file.txt"  
        
    - name: rm /root/test_any_file.txt
      file:
        path: /root/test_any_file.txt
        state: absent

    - name: stage 2, part 1
      shell:
        echo "Hello_world !!!" > /root/test_any_file.txt 2>&1

